- name: apache2_install
  apt:
    name: apache2
    state: present
- file:
    path: /var/www/html/index.html
    state: absent
- name: deploy_code
  copy:
    src: /home/ubuntu/ansible/roles/apache2/files/index.html
    dest: /var/www/html/
- name: deploy_code
  template:
       src: /home/ubuntu/ansible/roles/apache2/templates/hello.html.j2
       dest: /var/www/html
- name: install_packg
  apt:
    name: "{{packg_cmd}}"
    state: present
  notify:
  - restart_apache2
